### ISSUE TITLE
api pay ( retrait cash to cash )

### ISSUE THREAD

**Issue by benoptimus** [Kodelines/money-transactions-platform#11]
En appelant cette api j'ai cette erreur : {"response_code": "100", "response_text": "[\"{'destination_content_object': {'identification_document_delivery_date': ['Missing data for required field.'], 'identification_document_deleivery_date': ['Unknown field.']}}\"]"}

dans le payload l'information est bien la pourtant.

**Comment by williamsko** [comment]
Il dit que tu as envoyé cette information `identification_document_deleivery_date` au lieu de `identification_document_delivery_date`
