### ISSUE TITLE
Api customer/wallet/create/ {'identification_document_deleivery_date': ['Missing data for required field.']

### ISSUE THREAD

**Issue by benoptimus** [Kodelines/money-transactions-platform#2]
{'identification_document_deleivery_date': ['Missing data for required field.'] error

payload post : { identification_number: '664646',
  address: 'dakar',
  first_name: 'sd',
  last_name: 'ds',
  identification_type: 'PP',
  identification_document_delivery_date: '2020-03-27',
  identification_document_expiry_date: '2022-05-27',
  issuer_country: 'SN',
  country: 'SN',
  email: 'test@monnamon.com',
  phone_number: 'xxxxxxx' }

the right name should be identification_document_delivery_date instead of identification_document_deleivery_date

**Comment by williamsko** [comment]
OK. sûrement un problème d'orthographe. Je corrige .
Thanks

**Comment by williamsko** [comment]
Tu peux tester maintenant  :)

**Comment by benoptimus** [comment]
c'est ok.
