### ISSUE TITLE
customer/wallet/login

### ISSUE THREAD

**Issue by benoptimus** [Kodelines/money-transactions-platform#4]
reponse de l'api : { address: 'dkr',
  created: '2020-05-27T16:37:58.497642',
  id: 1,
  identification_document_delivery_date: '2020-05-27',
  identification_document_expiry_date: '2020-05-27',
  identification_number: 'fdgdsf',
  identification_type: 'PP',
  phone_number: '775019661',
  reponse_code: '000',
  resource_uri: '/api/v1/customer/1/',
  status: true,
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiY29kZSI6Ijc3NTAxOTY2MSIsImV4cCI6MTU5MzE5MjA3OH0.huMHXbxVbOpfYI9zm6idsiT6ZPrgaygMFBE7jVGk2EU',
  updated: '2020-05-27T17:16:28.840877' }

reponse_code au lieu de response_code.

Il faut aussi renvoyer les autres informations associees à l'utilisateur. Nom, Prenom, enfin toute les infos que l'on peut avoir du customer.

**Comment by williamsko** [comment]
C'est bon je viens de rajouter `first_name` et `last_name`.
De plus `reponse_code`  a été remplacé par `response_code`
