### ISSUE TITLE
api cash_to_bank

### ISSUE THREAD

**Issue by benoptimus** [Kodelines/money-transactions-platform#6]
Il ya cette erreur là : {"error_message": "'NoneType' object has no attribute 'split'", "traceback": "Traceback (most recent call last):\n\n File \"/root/environments/env_monnamon_backend/lib/python3.6/site-packages/tastypie/resources.py\", line 227, in wrapper\n response = callback(request, *args, **kwargs)\n\n File \"/root/src/money-transactions-platform/apps/api/transaction_api.py\", line 53, in create\n response = create_transaction(self, payload, request)\n\n File \"/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py\", line 123, in create\n _validate_transaction_payload(payload.copy())\n\n File \"/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py\", line 36, in _validate_transaction_payload\n validator_klass = _get_validator_class(transaction_type)\n\n File \"/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py\", line 27, in _get_validator_class\n validator = convert_snake_to_camel_case(transaction_type)\n\n File \"/root/src/money-transactions-platform/apps/core/utils/string.py\", line 41, in convert_snake_to_camel_case\n return ''.join(x.capitalize() or '_' for x in word.split('_'))\n\nAttributeError: 'NoneType' object has no attribute 'split'\n"}

**Comment by williamsko** [comment]
> Il ya cette erreur là : {"error_message": "'NoneType' object has no attribute 'split'", "traceback": "Traceback (most recent call last):\n\n File "/root/environments/env_monnamon_backend/lib/python3.6/site-packages/tastypie/resources.py", line 227, in wrapper\n response = callback(request, *args, **kwargs)\n\n File "/root/src/money-transactions-platform/apps/api/transaction_api.py", line 53, in create\n response = create_transaction(self, payload, request)\n\n File "/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py", line 123, in create\n _validate_transaction_payload(payload.copy())\n\n File "/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py", line 36, in _validate_transaction_payload\n validator_klass = _get_validator_class(transaction_type)\n\n File "/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py", line 27, in _get_validator_class\n validator = convert_snake_to_camel_case(transaction_type)\n\n File "/root/src/money-transactions-platform/apps/core/utils/string.py", line 41, in convert_snake_to_camel_case\n return ''.join(x.capitalize() or '_' for x in word.split('_'))\n\nAttributeError: 'NoneType' object has no attribute 'split'\n"}

Il faut bien mettre le type de transaction : `CASH_TO_BANK_ACCOUNT`

**Comment by benoptimus** [comment]
Apres quelque correction, j'ai cette erreur là: 

{"error_message": "module 'apps.transaction.domain.transaction_domain' has no attribute 'get_cash_to_bank_account_fee_payload'", "traceback": "Traceback (most recent call last):\n\n File \"/root/environments/env_monnamon_backend/lib/python3.6/site-packages/tastypie/resources.py\", line 227, in wrapper\n response = callback(request, *args, **kwargs)\n\n File \"/root/src/money-transactions-platform/apps/api/transaction_api.py\", line 54, in create\n response = create_transaction(self, payload, request)\n\n File \"/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py\", line 128, in create\n transaction = _create_agent_transaction(payload, token)\n\n File \"/root/src/money-transactions-platform/apps/transaction/decorator/transaction_decorator.py\", line 8, in modified_function\n return function(payload, token)\n\n File \"/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py\", line 150, in _create_agent_transaction\n fee_calculation_payload = get_fee_calculation_payload(payload)\n\n File \"/root/src/money-transactions-platform/apps/transaction/domain/transaction_domain.py\", line 59, in get_fee_calculation_payload\n method = getattr(module, 'get_{0}_fee_payload'.format(payload.get('type').lower()))\n\nAttributeError: module 'apps.transaction.domain.transaction_domain' has no attribute 'get_cash_to_bank_account_fee_payload'\n"}

**Comment by williamsko** [comment]
Tu peux retester stp

**Comment by benoptimus** [comment]
> Tu peux retester stp

toujours pareil. le payload:

{'source_content_object': {'first_name': 'test', 'last_name': 'test', 'phone_number': '+221 78 014 89 60', 'address': 'echo', 'identification_number': '65374657465', 'identification_type': 'PP', 'issuer_country': 'SN', 'identification_document_delivery_date': '2020-06-12', 'identification_document_expiry_date': '2025-06-12'}, 'destination_content_object': {'first_name': 'hello', 'last_name': 'world', 'phone_number': '+221 76 551 44 78', 'address': 'dakr'}, 'type': 'CASH_TO_BANK_ACCOUNT', 'source_country': 'SN', 'destination_country': 'SN', 'amount': '1000', 'source_revenu': '0', 'motif_envoi': '0', 'bank_name': 'ecobank', 'rib': '545646546546'}

l'erreur 

{"error_message": "module 'apps.transaction.domain.transaction_domain' has no attribute 'get_source_and_destination_of_cash_to_bank_account'", "traceback": "Traceback (most recent call last):\n\n File \"/root/environments/env_monnamon_backend/lib/python3.6/site-packages/tastypie/resources.py\", line 227, in wrapper\n response = callback(request, *args, **kwargs)\n\n File \"/root/src/money-transactions-platform/apps/api/transaction_api.py\", line 53, in create\n response = create_transaction(self, payload, request)\n\n File \"/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py\", line 128, in create\n transaction = _create_agent_transaction(payload, token)\n\n File \"/root/src/money-transactions-platform/apps/transaction/decorator/transaction_decorator.py\", line 8, in modified_function\n return function(payload, token)\n\n File \"/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py\", line 156, in _create_agent_transaction\n transaction = create_transaction(payload, agent)\n\n File \"/root/src/money-transactions-platform/apps/transaction/domain/transaction_domain.py\", line 185, in create_transaction\n return method(payload, executer)\n\n File \"/root/src/money-transactions-platform/apps/transaction/domain/transaction_domain.py\", line 212, in _create_cash_to_bank_account_transaction\n payload.copy())\n\n File \"/root/src/money-transactions-platform/apps/transaction/domain/transaction_domain.py\", line 128, in get_source_and_destination_of_transaction\n method = getattr(module, 'get_source_and_destination_of_{0}'.format(payload.get('type').lower()))\n\nAttributeError: module 'apps.transaction.domain.transaction_domain' has no attribute 'get_source_and_destination_of_cash_to_bank_account'\n"}.

Tu pourras tester apres correction sur l'adresse http://217.69.6.52:8000/, test-agent/testpasser les credentials du compte agent utilisé pour faire les tests.

**Comment by williamsko** [comment]
hello , tu peux retry le boss . Merci

**Comment by benoptimus** [comment]
{"error_message": "'Transaction' object has no attribute 'operation_amount'", "traceback": "Traceback (most recent call last):\n\n File \"/root/environments/env_monnamon_backend/lib/python3.6/site-packages/tastypie/resources.py\", line 227, in wrapper\n response = callback(request, *args, **kwargs)\n\n File \"/root/src/money-transactions-platform/apps/api/transaction_api.py\", line 45, in create\n response = create_transaction(self, payload, request)\n\n File \"/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py\", line 141, in create\n _response = _addtitional_transactions_informations(transaction, payload)\n\n File \"/root/src/money-transactions-platform/apps/transaction/controller/transaction_controller.py\", line 100, in _addtitional_transactions_informations\n payload.update({'operation_amount': transaction.operation_amount})\n\nAttributeError: 'Transaction' object has no attribute 'operation_amount'\n"}

l'erreur lors de l'operation

**Comment by williamsko** [comment]
Ce souci a été déjà réglé
